_includes/footer.html
assets/style.css
mlists/index.html
security/index.html

Added security page in line with the new SECURITY.md guidelines.

Add security page

---

development/index.html

I have been working on a language binding to utilize Open vSwitch from the Lua language.  I'd like to make that work readily discoverable for those who might be interested in it.

Added reference to LJIT2ovs lua language binding

---

index.html

Signed-off-by: Alex Wang <ee07b291@gmail.com>

index.html: Add Patchwork description and link.

---

_data/nav.yml
support/ovscon2021/index.html

Start on the conf. page for OVS Conf 2021.

OVS Conf 2021 start

---

support/ovscon2021/index.html

This can help give some insight to the community for who is presenting
as well as giving credit to those companies that let their employees
participate.

ovscon2021: Include company affiliations

---

support/ovscon2021/index.html

Add a tentative schedule for the two days.

ovscon2021: Tentative schedule

---

support/ovscon2021/index.html

ovscon: correct site image

---

support/ovscon2021/index.html

This was actually a full talk, but got recorded as lightning.

schedule: fix the nodus talk

---

support/ovscon2021/index.html

ovs21-schedule: move Haresh's talk by request

---

support/ovscon2022/index.html

Signed-off-by: Michael Santana <msantana@redhat.com>

Fix proposal deadline for ovsconf 2022

---

support/ovscon2022/index.html

Update conference deadlines and add registration link.

---

support/ovscon2022/index.html

This includes the talk name, speaker, affiliation, and abstracts.
Schedule will be forthcoming

ovscon2022: Announce talks

---

support/ovscon2022/index.html

Post Chris Wright keynote announcement, and the dinner / food schedule after confirming some of the food times.
A talk fron NVIDIA is also added in place of the pulled talk.
Insert many spaces in one of the talk cells to make it line up with the other tables (request from Rashid)

schedule: round two of updates

---

support/ovscon2022/index.html

Reported-by: Dumitru Ceara <dceara@redhat.com>
Reported-by: Hareesh Puthalath <hareeshp@nvidia.com>
Reported-by: Ihar Hrachyshka <ihrachys@redhat.com>

ovscon2022: Fix some misattributions, and spelling issues

---

support/ovscon2022/index.html

ovscon2022: Set up the video presentation links.

---

support/ovscon2023/index.html

ovsconf 2023: Add abstracts

---

support/ovscon2023/index.html

These were missed the first time around.

ovsconf 2023: Add schedule and 2 talks

---

support/ovscon2023/index.html

Some schedule conflicts caused problems for some speakers. Rescheduling to get things worked out.  Will circle back with presenters.

ovsconf 2023: schedule update

---

support/ovscon2023/index.html

ovsconf 2023: Add links to youtube videos

---

support/ovscon2024/index.html

conf 2024: Fix logo.

---

support/ovscon2024/index.html

Agreed by the speakers during day one.

ovscon2024: Swap the Retis talk with the Scalable AI talk

---

support/ovscon2024/index.html

Add the videos.  To do - add the slides.

ovscon2024: Update the conference page with closing details
